CREATE VIEW [dbo].[V_ORDERS]
as
WITH CTE AS(
		SELECT
		ORD.ID,
		SUM( ora.VALUEBRUTTO) VALUEBRUTTO,
		SUM( ora.VALUENETTO) VALUENETTO
	FROM dbo.ORDERS ORD
	JOIN dbo.ORDER_ORDERARTICLES ORDA on ORDA.ORDERID = ORD.ID
	JOIN dbo.V_ORDERARTICLES ORA ON ORA.ID = ORDA.ORDERARTICLEID
	GROUP BY ORD.ID
	)
	SELECT
	ORD.ID,
	ORD.DATE,
	C.NAME + C.SURNAME CLIENTNAME,
	CT.VALUEBRUTTO,
	CT.VALUENETTO
	FROM dbo.ORDERS ORD
	JOIN dbo.CLIENTS C ON C.ID = ORD.CLIENTID
	JOIN CTE CT on CT.ID = ORD.ID
