CREATE TABLE [dbo].[ORDERS]
(
	[ID]            INT                 IDENTITY (1, 1) NOT NULL,
	[DATE]			DATETIME DEFAULT getdate()			NOT NULL,
	[CLIENTID]      INT									NOT NULL,

	CONSTRAINT [PK_ORDERS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ORDERS_CLIENTS] FOREIGN KEY ([CLIENTID]) REFERENCES [dbo].[CLIENTS] ([ID]),
)
